spring:
 profiles:
  active:
  - dev
---
server:
 port: 8201
spring:
 profiles: dev
 application:
  name: servicecloud-config-client
---
server:
 port: 8202
spring:
 profiles: test
 application:
  name: servicecloud-config-client